### ISSUE TITLE
aggregate_spatial for a large-ish amount of Points incorrectly marked as "error"

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#136]
Batch job fc13f354-7da8-424f-9fe6-42bf80a2ab90 finishes successfully in YARN but the job is still marked as "error" by the job tracker afterwards. According to the logs in Kibana we're bumping into the ZNode size limit again::

```
resuming with remaining jobs after failing to handle batch job fc13f354-7da8-424f-9fe6-42bf80a2ab90:
Traceback (most recent call last):
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/job_tracker.py", line 126, in update_statuses
    registry.patch(job_id, user_id, **result_metadata)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/job_registry.py", line 139, in patch
    self._update({**job_info, **kwargs}, version)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/job_registry.py", line 287, in _update
    self._zk.set(path, data, version)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/kazoo/client.py", line 1359, in set
    return self.set_async(path, value, version).get()
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/kazoo/handlers/utils.py", line 75, in get
    raise self._exception
kazoo.exceptions.ConnectionLoss
```

**Comment by bossie** [comment]
Batch job entity: [fc13f354-7da8-424f-9fe6-42bf80a2ab90.json.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/8371523/fc13f354-7da8-424f-9fe6-42bf80a2ab90.json.txt)

Input geometries (1421 points features): [fc13f354-7da8-424f-9fe6-42bf80a2ab90.geojson.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/8371527/fc13f354-7da8-424f-9fe6-42bf80a2ab90.geojson.txt)

Geometries written to job_metadata.json and subsequently patched in the ZNode: [fc13f354-7da8-424f-9fe6-42bf80a2ab90_out.geojson.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/8371537/fc13f354-7da8-424f-9fe6-42bf80a2ab90_out.geojson.txt)

The output polygons are the input points buffered because points are not supported all the way down. The buffering currently results in a round-ish polygon but this means that we go from 1 x/y pair to 64 x/y pairs per point and a very large geometry.
