### ISSUE TITLE
improve job logs in job_tracker, async_task etc

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#141]
In at least one case, Py4J won't propagate additional info/helpful context to the caller:

```
failed to handle polling batch processes for batch job 1d5dc3ec-d4dd-48c2-9a8c-181cd6ceb358:
Traceback (most recent call last):
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py", line 160, in main
    batch_jobs().poll_sentinelhub_batch_processes(job_info)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 812, in poll_sentinelhub_batch_processes
    caching_service.download_and_cache_results(bucket_name, subfolder, collecting_folder)
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py", line 1309, in __call__
    return_value = get_return_value(
  File "/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/protocol.py", line 334, in get_return_value
    raise Py4JError(
py4j.protocol.Py4JError: An error occurred while calling o1.download_and_cache_results
```

Py4J will, however, log this error internally (mail upon unsuccessful completion of async task):
```
{"asctime": "2022-04-11T12:37:24+0200", "name": "openeogeotrellis.backend", "levelname": "DEBUG", "message": "Sentinel Hub batch process statuses for batch job 1d5dc3ec-d4dd-48c2-9a8c-181cd6ceb358: ['DONE']", "job_id": "1d5dc3ec-d4dd-48c2-9a8c-181cd6ceb358"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "py4j.java_gateway", "levelname": "INFO", "message": "Error while receiving.", "exc_info": "Traceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1212, in send_command\n    raise Py4JNetworkError(\"Answer from Java side is empty\")\npy4j.protocol.Py4JNetworkError: Answer from Java side is empty"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "root", "levelname": "ERROR", "message": "Exception while sending command.", "exc_info": "Traceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1212, in send_command\n    raise Py4JNetworkError(\"Answer from Java side is empty\")\npy4j.protocol.Py4JNetworkError: Answer from Java side is empty\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1038, in send_command\n    response = connection.send_command(command)\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1216, in send_command\n    raise Py4JNetworkError(\npy4j.protocol.Py4JNetworkError: Error while receiving"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "__main__", "levelname": "ERROR", "message": "failed to handle polling batch processes for batch job 1d5dc3ec-d4dd-48c2-9a8c-181cd6ceb358:\nTraceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py\", line 160, in main\n    batch_jobs().poll_sentinelhub_batch_processes(job_info)\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py\", line 812, in poll_sentinelhub_batch_processes\n    caching_service.download_and_cache_results(bucket_name, subfolder, collecting_folder)\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1309, in __call__\n    return_value = get_return_value(\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/protocol.py\", line 334, in get_return_value\n    raise Py4JError(\npy4j.protocol.Py4JError: An error occurred while calling o1.download_and_cache_results\n", "job_id": "1d5dc3ec-d4dd-48c2-9a8c-181cd6ceb358"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "kazoo.client", "levelname": "INFO", "message": "Connecting to [epod-master1.vgt.vito.be](http://epod-master1.vgt.vito.be/)(192.168.207.56):2181, use_ssl: False"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "kazoo.client", "levelname": "INFO", "message": "Zookeeper connection established, state: CONNECTED"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "kazoo.client", "levelname": "INFO", "message": "Closing connection to [epod-master1.vgt.vito.be:2181](http://epod-master1.vgt.vito.be:2181/)"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "kazoo.client", "levelname": "INFO", "message": "Zookeeper session closed, state: CLOSED"}
{"asctime": "2022-04-11T12:41:22+0200", "name": "__main__", "levelname": "ERROR", "message": "An error occurred while calling o1.download_and_cache_results", "exc_info": "Traceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/async_task.py\", line 160, in main\n    batch_jobs().poll_sentinelhub_batch_processes(job_info)\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/openeogeotrellis/backend.py\", line 812, in poll_sentinelhub_batch_processes\n    caching_service.download_and_cache_results(bucket_name, subfolder, collecting_folder)\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1309, in __call__\n    return_value = get_return_value(\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/protocol.py\", line 334, in get_return_value\n    raise Py4JError(\npy4j.protocol.Py4JError: An error occurred while calling o1.download_and_cache_results"}
{"asctime": "2022-04-11T12:41:23+0200", "name": "py4j.java_gateway", "levelname": "ERROR", "message": "An error occurred while trying to connect to the Java server ([127.0.0.1:38637](http://127.0.0.1:38637/))", "exc_info": "Traceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 982, in _get_connection\n    connection = self.deque.pop()\nIndexError: pop from an empty deque\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1120, in start\n    self.socket.connect((self.address, self.port))\nConnectionRefusedError: [Errno 111] Connection refused"}
{"asctime": "2022-04-11T12:41:23+0200", "name": "py4j.java_gateway", "levelname": "ERROR", "message": "An error occurred while trying to connect to the Java server ([127.0.0.1:38637](http://127.0.0.1:38637/))", "exc_info": "Traceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 982, in _get_connection\n    connection = self.deque.pop()\nIndexError: pop from an empty deque\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/scripts/OpenEO/dev/venv/lib/python3.8/site-packages/py4j/java_gateway.py\", line 1120, in start\n    self.socket.connect((self.address, self.port))\nConnectionRefusedError: [Errno 111] Connection refused"}
```

These also end up in Elasticsearch but since Py4J's logs don't carry a job_id, they don't come up upon filter for this job_id. Find a way to include the job_id in logs that are emitted in the context of a particular batch job, also for code that is not ours.

**Comment by bossie** [comment]
Possibly: https://stackoverflow.com/questions/64348644/set-default-logging-extra-for-pythons-logger-object

**Comment by soxofaan** [comment]
FYI: automatically injecting batch job id and user id in batch job logs from python is part of what I'm working on in https://github.com/Open-EO/openeo-python-driver/issues/111
