### ISSUE TITLE
merge_cubes fails with wetsnow process graph

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-geopyspark-driver#163]
I refer to this notebook:
https://github.com/openEOPlatform/LPS_presentations/blob/main/classrooms/EURAC_advanced_processing/openEO%20Platform%20-%20Advanced%20data%20processing%20-%20Snow%20monitoring.ipynb

I get different errors if I try to run it as a sync call or as a batch job.
The final `merge_cubes` should merge two datacubes with dimensions `['t','y','x']` but it fails.

<details>
  <summary>Process graph:</summary>
  
  ```javascript
  {
    "process_graph": {
      "1": {
        "process_id": "save_result",
        "arguments": {
          "data": {
            "from_node": "mergecubes3"
          },
          "format": "NETCDF"
        },
        "result": true
      },
      "loadcollection1": {
        "process_id": "load_collection",
        "arguments": {
          "bands": [
            "VV",
            "VH"
          ],
          "id": "S1_GRD_SIGMA0_DESCENDING",
          "spatial_extent": {
            "west": 9.663849,
            "east": 10.200806,
            "south": 46.009728,
            "north": 46.135486
          },
          "temporal_extent": [
            "2020-11-01",
            "2021-06-30"
          ]
        }
      },
      "loadcollection2": {
        "process_id": "load_collection",
        "arguments": {
          "bands": [
            "angle"
          ],
          "id": "S1_GRD_SIGMA0_DESCENDING",
          "spatial_extent": {
            "west": 9.663849,
            "east": 10.200806,
            "south": 46.009728,
            "north": 46.135486
          },
          "temporal_extent": [
            "2020-11-01",
            "2020-11-10"
          ]
        }
      },
      "loadcollection3": {
        "process_id": "load_collection",
        "arguments": {
          "bands": [
            "SCL"
          ],
          "id": "SENTINEL2_L2A",
          "spatial_extent": {
            "west": 9.663849,
            "east": 10.200806,
            "south": 46.009728,
            "north": 46.135486
          },
          "temporal_extent": [
            "2020-11-01",
            "2021-06-30"
          ]
        }
      },
      "apply1": {
        "process_id": "apply",
        "arguments": {
          "data": {
            "from_node": "loadcollection1"
          },
          "process": {
            "process_graph": {
              "log1": {
                "process_id": "log",
                "arguments": {
                  "base": 10,
                  "x": {
                    "from_parameter": "x"
                  }
                }
              },
              "multiply1": {
                "process_id": "multiply",
                "arguments": {
                  "x": 10,
                  "y": {
                    "from_node": "log1"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension2": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "loadcollection2"
          },
          "dimension": "t",
          "reducer": {
            "process_graph": {
              "min1": {
                "process_id": "min",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension7": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "loadcollection3"
          },
          "dimension": "bands",
          "reducer": {
            "process_graph": {
              "arrayelement7": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 0
                }
              },
              "eq1": {
                "process_id": "eq",
                "arguments": {
                  "x": {
                    "from_node": "arrayelement7"
                  },
                  "y": 11
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension1": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "apply1"
          },
          "dimension": "t",
          "reducer": {
            "process_graph": {
              "mean1": {
                "process_id": "mean",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension3": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "reducedimension2"
          },
          "dimension": "bands",
          "reducer": {
            "process_graph": {
              "arrayelement1": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 0
                }
              },
              "divide1": {
                "process_id": "divide",
                "arguments": {
                  "x": {
                    "from_node": "arrayelement1"
                  },
                  "y": 1000
                }
              },
              "subtract2": {
                "process_id": "subtract",
                "arguments": {
                  "x": 45,
                  "y": {
                    "from_node": "divide1"
                  }
                }
              },
              "multiply2": {
                "process_id": "multiply",
                "arguments": {
                  "x": {
                    "from_node": "subtract2"
                  },
                  "y": 0.04
                }
              },
              "add1": {
                "process_id": "add",
                "arguments": {
                  "x": {
                    "from_node": "multiply2"
                  },
                  "y": 1
                }
              },
              "multiply3": {
                "process_id": "multiply",
                "arguments": {
                  "x": 0.5,
                  "y": {
                    "from_node": "add1"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension4": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "reducedimension2"
          },
          "dimension": "bands",
          "reducer": {
            "process_graph": {
              "arrayelement2": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 0
                }
              },
              "divide2": {
                "process_id": "divide",
                "arguments": {
                  "x": {
                    "from_node": "arrayelement2"
                  },
                  "y": 1000
                }
              },
              "lt1": {
                "process_id": "lt",
                "arguments": {
                  "x": {
                    "from_node": "divide2"
                  },
                  "y": 20
                },
                "result": true
              }
            }
          }
        }
      },
      "reducedimension5": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "reducedimension2"
          },
          "dimension": "bands",
          "reducer": {
            "process_graph": {
              "arrayelement3": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 0
                }
              },
              "divide3": {
                "process_id": "divide",
                "arguments": {
                  "x": {
                    "from_node": "arrayelement3"
                  },
                  "y": 1000
                }
              },
              "lt2": {
                "process_id": "lt",
                "arguments": {
                  "x": {
                    "from_node": "divide3"
                  },
                  "y": 45
                },
                "result": true
              }
            }
          }
        }
      },
      "aggregatetemporalperiod2": {
        "process_id": "aggregate_temporal_period",
        "arguments": {
          "data": {
            "from_node": "reducedimension7"
          },
          "period": "week",
          "reducer": {
            "process_graph": {
              "max1": {
                "process_id": "max",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "mergecubes1": {
        "process_id": "merge_cubes",
        "arguments": {
          "cube1": {
            "from_node": "apply1"
          },
          "cube2": {
            "from_node": "reducedimension1"
          },
          "overlap_resolver": {
            "process_graph": {
              "subtract1": {
                "process_id": "subtract",
                "arguments": {
                  "x": {
                    "from_parameter": "x"
                  },
                  "y": {
                    "from_parameter": "y"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "mask1": {
        "process_id": "mask",
        "arguments": {
          "data": {
            "from_node": "reducedimension3"
          },
          "mask": {
            "from_node": "reducedimension4"
          },
          "replacement": 1
        }
      },
      "mask2": {
        "process_id": "mask",
        "arguments": {
          "data": {
            "from_node": "mask1"
          },
          "mask": {
            "from_node": "reducedimension5"
          },
          "replacement": 0.5
        }
      },
      "mergecubes2": {
        "process_id": "merge_cubes",
        "arguments": {
          "cube1": {
            "from_node": "mergecubes1"
          },
          "cube2": {
            "from_node": "mask2"
          }
        }
      },
      "reducedimension6": {
        "process_id": "reduce_dimension",
        "arguments": {
          "data": {
            "from_node": "mergecubes2"
          },
          "dimension": "bands",
          "reducer": {
            "process_graph": {
              "arrayelement4": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 2
                }
              },
              "arrayelement5": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 1
                }
              },
              "multiply4": {
                "process_id": "multiply",
                "arguments": {
                  "x": {
                    "from_node": "arrayelement4"
                  },
                  "y": {
                    "from_node": "arrayelement5"
                  }
                }
              },
              "subtract3": {
                "process_id": "subtract",
                "arguments": {
                  "x": 1,
                  "y": {
                    "from_node": "arrayelement4"
                  }
                }
              },
              "arrayelement6": {
                "process_id": "array_element",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  },
                  "index": 0
                }
              },
              "multiply5": {
                "process_id": "multiply",
                "arguments": {
                  "x": {
                    "from_node": "subtract3"
                  },
                  "y": {
                    "from_node": "arrayelement6"
                  }
                }
              },
              "add2": {
                "process_id": "add",
                "arguments": {
                  "x": {
                    "from_node": "multiply4"
                  },
                  "y": {
                    "from_node": "multiply5"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "aggregatetemporalperiod1": {
        "process_id": "aggregate_temporal_period",
        "arguments": {
          "data": {
            "from_node": "reducedimension6"
          },
          "period": "week",
          "reducer": {
            "process_graph": {
              "mean2": {
                "process_id": "mean",
                "arguments": {
                  "data": {
                    "from_parameter": "data"
                  }
                },
                "result": true
              }
            }
          }
        }
      },
      "apply2": {
        "process_id": "apply",
        "arguments": {
          "data": {
            "from_node": "aggregatetemporalperiod1"
          },
          "process": {
            "process_graph": {
              "lte1": {
                "process_id": "lte",
                "arguments": {
                  "x": {
                    "from_parameter": "x"
                  },
                  "y": -2
                },
                "result": true
              }
            }
          }
        }
      },
      "apply3": {
        "process_id": "apply",
        "arguments": {
          "data": {
            "from_node": "aggregatetemporalperiod1"
          },
          "process": {
            "process_graph": {
              "gt1": {
                "process_id": "gt",
                "arguments": {
                  "x": {
                    "from_parameter": "x"
                  },
                  "y": -2
                },
                "result": true
              }
            }
          }
        }
      },
      "mask3": {
        "process_id": "mask",
        "arguments": {
          "data": {
            "from_node": "aggregatetemporalperiod1"
          },
          "mask": {
            "from_node": "apply2"
          },
          "replacement": 10
        }
      },
      "mask4": {
        "process_id": "mask",
        "arguments": {
          "data": {
            "from_node": "mask3"
          },
          "mask": {
            "from_node": "apply3"
          },
          "replacement": 20
        }
      },
      "mergecubes3": {
        "process_id": "merge_cubes",
        "arguments": {
          "cube1": {
            "from_node": "mask4"
          },
          "cube2": {
            "from_node": "aggregatetemporalperiod2"
          },
          "overlap_resolver": {
            "process_graph": {
              "multiply6": {
                "process_id": "multiply",
                "arguments": {
                  "x": {
                    "from_parameter": "x"
                  },
                  "y": {
                    "from_parameter": "y"
                  }
                },
                "result": true
              }
            }
          }
        }
      }
    },
    "parameters": []
  }
  ```
</details>

sync call log:
`Merging cubes with an overlap resolver is only supported when band counts are the same. I got: 0 and 1`

batch job log:

```
error processing batch job Traceback (most recent call last): File "batch_job.py", line 319, in main run_driver() File "batch_job.py", line 292, in run_driver run_job( File "/data3/hadoop/yarn/local/usercache/michele.claus/appcache/application_1652703749569_0895/container_e5025_1652703749569_0895_01_000006/venv/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 41, in memory_logging_wrapper return function(*args, **kwargs) File "batch_job.py", line 388, in run_job assets_metadata = result.write_assets(str(output_file)) File "/data3/hadoop/yarn/local/usercache/michele.claus/appcache/application_1652703749569_0895/container_e5025_1652703749569_0895_01_000006/venv/lib/python3.8/site-packages/openeo_driver/save_result.py", line 110, in write_assets return self.cube.write_assets(filename=directory, format=self.format, format_options=self.options) File "/data3/hadoop/yarn/local/usercache/michele.claus/appcache/application_1652703749569_0895/container_e5025_1652703749569_0895_01_000006/venv/lib/python3.8/site-packages/openeogeotrellis/geopysparkdatacube.py", line 1656, in write_assets asset_paths = self._get_jvm().org.openeo.geotrellis.netcdf.NetCDFRDDWriter.saveSingleNetCDF(max_level.srdd.rdd(), File "/opt/spark3_2_0/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1309, in __call__ return_value = get_return_value( File "/opt/spark3_2_0/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 326, in get_return_value raise Py4JJavaError( py4j.protocol.Py4JJavaError: An error occurred while calling z:org.openeo.geotrellis.netcdf.NetCDFRDDWriter.saveSingleNetCDF. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 40 in stage 162.0 failed 4 times, most recent failure: Lost task 40.4 in stage 162.0 (TID 5335) (epod121.vgt.vito.be executor 149): ExecutorLostFailure (executor 149 exited caused by one of the running tasks) Reason: Container from a bad node: container_e5025_1652703749569_0895_01_000227 on host: epod121.vgt.vito.be. Exit status: 143. Diagnostics: [2022-05-16 17:41:38.334]Container killed on request. Exit code is 143 [2022-05-16 17:41:38.355]Container exited with a non-zero exit code 143. [2022-05-16 17:41:38.357]Killed by external signal . Driver stacktrace: at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2403) at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2352) at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2351) at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62) at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49) at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2351) at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1109) at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1109) at scala.Option.foreach(Option.scala:407) at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1109) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2591) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2533) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2522) at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49) at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:898) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2214) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2235) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2254) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2279) at org.apache.spark.rdd.RDD.count(RDD.scala:1253) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.cacheAndRepartition(NetCDFRDDWriter.scala:198) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter$.saveSingleNetCDF(NetCDFRDDWriter.scala:140) at org.openeo.geotrellis.netcdf.NetCDFRDDWriter.saveSingleNetCDF(NetCDFRDDWriter.scala) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357) at py4j.Gateway.invoke(Gateway.java:282) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182) at py4j.ClientServerConnection.run(ClientServerConnection.java:106) at java.base/java.lang.Thread.run(Thread.java:829) Your batch job failed because workers used too much Python memory. The same task was attempted multiple times. Consider increasing executor-memoryOverhead or contact the developers to investigate.

    error

    ID: error
```

**Comment by clausmichele** [comment]
Hi @jdries, I've just tried again with the same code and I get this error:

`OpenEoApiError: [400] unknown: Merging cubes with an overlap resolver is only supported when band counts are the same. I got: 0 and 1`

**Comment by jdries** [comment]
@clausmichele  integration tests were a bit slow to deploy today, but I just tried twice and didn't get an error. Can you try again as well?

**Comment by clausmichele** [comment]
It worked! Thanks a lot for the support. Please let me know when it will also be available on the production back-end.
