### ISSUE TITLE
Automate deployment of OpenEO support apps

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#174]
https://jira.vito.be/browse/EP-4135

**Comment by bossie** [comment]
OpenEO process group: https://nifi-prod-01.vgt.vito.be:8443/nifi/?processGroupId=64e7c8f2-0180-1000-0000-000012b8f017&componentIds=

**Comment by bossie** [comment]
TODO:
- address TODOs in cleaner-docker.sh
- add scripts for async_task
- restore filebeat logging

**Comment by bossie** [comment]
User that wrote items in /tmp_epod/openeo_collecting and /tmp_epod/openeo_assembled is different from the one that is trying to clean them up (nifi-intern resp. nifi-prod):

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 64, in <module>
    main()
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 59, in main
    remove_batch_jobs_before(max_date, java_gateway.jvm)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 24, in remove_batch_jobs_before
    batch_jobs.delete_jobs_before(upper)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1847, in delete_jobs_before
    self._delete_job(job_id=job_info['job_id'], user_id=job_info['user_id'], propagate_errors=True)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1778, in _delete_job
    self.delete_batch_process_dependency_sources(job_id, dependency_sources, propagate_errors)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1830, in delete_batch_process_dependency_sources
    shutil.rmtree(assembled_folder)
  File "/usr/lib64/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '20180822-32TPR_0_3.tif'
```

**Comment by bossie** [comment]
Created follow-up tickets #191 and #192.
