### ISSUE TITLE
investigate coherence collection

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#261]
I was forced to do this to make integrationtests pass:
https://git.vito.be/projects/BIGGEO/repos/openeo-collection-tests/commits/543c24b7379d2d8e855c7a4cbcc233ec08358cbf

The main issue is that for certain specific dates, we used to have data, but this is no longer returned.
I tried to reproduce it locally, but always got the data for those missing dates.

EDIT: isUTM flag was false when trying to reproduce, while it's set to true in prod!
```

def test_sigma0():
   
    import openeo
    connection = openeo.connect("openeo-dev.vito.be").authenticate_oidc()

    spatial_extent_full ={'west': 4.128, 'south': 51.08, 'east': 4.205523809946203, 'north': 51.126}
   
   
    cube = connection.load_collection("TERRASCOPE_S1_SLC_COHERENCE_V1",temporal_extent=["2020-03-25","2020-03-25"],spatial_extent=spatial_extent_full)
   
    cube.download("coherence_full_batch14.nc",options=dict(overviews="OFF",strict_cropping=False))
```

Code I used to locally reproduce:
```


    val date = LocalDate.of(2020, 3, 25).atStartOfDay(UTC)

    val crs = CRS.fromEpsgCode(32631)
    
    val boundingBox = ProjectedExtent(Extent( 4.128, 51.268, 4.165523809946203, 51.27).reproject(LatLng,crs),crs )

    val dataCubeParameters = new DataCubeParameters
    dataCubeParameters.layoutScheme = "FloatingLayoutScheme"
    dataCubeParameters.globalExtent = Some(boundingBox)

    val result = LayerFixtures.coherenceLayerProviderUTM.readKeysToRasterSources(
      from = date,
      to = date,
      boundingBox,
      polygons = Array(MultiPolygon(boundingBox.extent.toPolygon())),
      polygons_crs = crs,
      zoom = 0,
      sc,
      Some(dataCubeParameters)
    )

    val fullCube = LayerFixtures.coherenceLayerProviderUTM.readMultibandTileLayer(
      from = date,
      to = date,
      boundingBox,
      polygons = Array(MultiPolygon(boundingBox.extent.toPolygon())),
      polygons_crs = crs,
      zoom = 0,
      sc,
      Some(dataCubeParameters)
    )
    fullCube.toSpatial().writeGeoTiff("/tmp/cube.tif")
    geotiff.saveRDDTemporal(fullCube,"/tmp/",cropBounds = Some(Extent(xmin=578689.9426662864, ymin=5680232.497089447, xmax=581311.0787154364, ymax=5680495.781299276)))

    val minKey = result._2.bounds.get.minKey

    val cols = math.ceil((boundingBox.extent.width / 10.0)/256.0)
    val rows = math.ceil((boundingBox.extent.height / 10.0)/256.0)

    assertEquals(0,minKey.col)
    assertEquals(0,minKey.row)
    assertEquals(crs,result._2.crs)
```

**Comment by jdries** [comment]
Another weird issue that only shows up for coherence, also in collection test:
```

java.io.IOException: Error while reading GridBounds(14376,1151,14631,1406) from: /data/MTDA/TERRASCOPE_Sentinel1/SLC_COHERENCE/2020/03/13/S1B_S1A_Coherence_20200307T172417_20200313T172441_ASC_88_V100/S1B_S1A_Coherence_20200307T172417_20200313T172441_ASC_88_V100_VV.tif
	at org.openeo.geotrellis.layers.BandCompositeRasterSource.read(FileLayerProvider.scala:95)
	at geotrellis.raster.RasterSource.read(RasterSource.scala:128)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.$anonfun$raster$1(RasterRegion.scala:44)
	at scala.Option.flatMap(Option.scala:271)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster$lzycompute(RasterRegion.scala:43)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster(RasterRegion.scala:41)
	at org.openeo.geotrellis.layers.FileLayerProvider$$anon$3.loadData(FileLayerProvider.scala:472)
	at org.openeo.geotrelliscommon.NoCloudFilterStrategy$.loadMasked(CloudFilterStrategy.scala:26)
	at org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$loadPartition$6(FileLayerProvider.scala:441)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at org.apache.spark.util.collection.CompactBuffer$$anon$1.foreach(CompactBuffer.scala:115)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.util.collection.CompactBuffer.foreach(CompactBuffer.scala:32)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at org.apache.spark.util.collection.CompactBuffer.flatMap(CompactBuffer.scala:32)
	at org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$loadPartition$1(FileLayerProvider.scala:414)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:659)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:650)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Suppressed: java.io.IOException: Error while reading GridBounds(14632,1151,14887,1406) from: /data/MTDA/TERRASCOPE_Sentinel1/SLC_COHERENCE/2020/03/13/S1B_S1A_Coherence_20200307T172417_20200313T172441_ASC_88_V100/S1B_S1A_Coherence_20200307T172417_20200313T172441_ASC_88_V100_VV.tif
		at org.openeo.geotrellis.layers.BandCompositeRasterSource.read(FileLayerProvider.scala:95)
		at geotrellis.raster.RasterSource.read(RasterSource.scala:128)
		at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.$anonfun$raster$1(RasterRegion.scala:44)
		at scala.Option.flatMap(Option.scala:271)
		at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster$lzycompute(RasterRegion.scala:43)
		at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster(RasterRegion.scala:41)
		at org.openeo.geotrellis.layers.FileLayerProvider$$anon$3.loadData(FileLayerProvider.scala:472)
		at org.openeo.geotrelliscommon.NoCloudFilterStrategy$.loadMasked(CloudFilterStrategy.scala:26)
		at org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$loadPartition$6(FileLayerProvider.scala:441)
		at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
		at scala.collection.Iterator.foreach(Iterator.scala:941)
		at scala.collection.Iterator.foreach$(Iterator.scala:941)
		at org.apache.spark.util.collection.CompactBuffer$$anon$1.foreach(CompactBuffer.scala:115)
		at scala.collection.IterableLike.foreach(IterableLike.scala:74)
		at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
		at org.apache.spark.util.collection.CompactBuffer.foreach(CompactBuffer.scala:32)
		at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
		at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
		at org.apache.spark.util.collection.CompactBuffer.flatMap(CompactBuffer.scala:32)
		at org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$loadPartition$1(FileLayerProvider.scala:414)
		at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:659)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
		at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:650)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
		... 8 more
	Caused by: java.util.NoSuchElementException: None.get
		at scala.None$.get(Option.scala:529)
		at scala.None$.get(Option.scala:527)
		at scala.collection.parallel.ParIterableLike.$anonfun$reduce$1(ParIterableLike.scala:376)
		at scala.collection.parallel.ParIterableLike$$anon$1$$anon$2.map(ParIterableLike.scala:308)
		at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:961)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
		at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:955)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
		at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
		at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
		at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:721)
		at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
		at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
		at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
		at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
		at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
		at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
		at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
		at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
		at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
		at scala.collection.parallel.ParIterableLike.reduce(ParIterableLike.scala:376)
		at scala.collection.parallel.ParIterableLike.reduce$(ParIterableLike.scala:375)
		at scala.collection.parallel.immutable.ParVector.reduce(ParVector.scala:42)
		at org.openeo.geotrellis.layers.BandCompositeRasterSource.read(FileLayerProvider.scala:90)
```

Also for:
java.io.IOException: Error while reading GridBounds(14376,1151,14631,1406) from: /data/MTDA/TERRASCOPE_Sentinel1/SLC_COHERENCE/2020/03/01/S1B_S1A_Coherence_20200224T172416_20200301T172441_ASC_88_V100/S1B_S1A_Coherence_20200224T172416_20200301T172441_ASC_88_V100_VV.tif

**Comment by jdries** [comment]
Done, added proposal to get more direct test coverage here:
https://github.com/Open-EO/openeo-geotrellis-extensions/issues/110
