### ISSUE TITLE
nightly cleaner is unable to remove randomforest.model/

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#265]
User openeo that runs nightly cleaner doesn't have permissions to remove (parts of) randomforest.model/. This also prevents removal of other batch jobs.

```
INFO:__main__:removing batch jobs before 2022-09-02 02:00:07.991842...
INFO:openeogeotrellis.backend:Deleted job [dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-efc36faeec0d4ef5938e67bb55034439](http://dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-efc36faeec0d4ef5938e67bb55034439)
INFO:openeogeotrellis.backend:Deleted job [dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-ce60f24dc4f24539b64dafe0efa35fbd](http://dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-ce60f24dc4f24539b64dafe0efa35fbd)
INFO:openeogeotrellis.backend:Deleted job [dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-09a59f858b9b4179acd01c3e632466f8](http://dfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd@egi.eu/j-09a59f858b9b4179acd01c3e632466f8)
INFO:openeogeotrellis.backend:Deleted job vdboschj/j-eca542a2d02147dc85662224f73faf14
WARNING:openeogeotrellis.backend:Could not recursively delete /data/projects/OpenEO/j-305816c41ecf463e8255c52ea6f7734c
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1987, in _delete_job
    shutil.rmtree(job_dir)
  File "/usr/lib64/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink([entry.name](http://entry.name/), dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '._SUCCESS.crc'
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 64, in <module>
    main()
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 59, in main
    remove_batch_jobs_before(max_date, java_gateway.jvm)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/cleaner.py", line 24, in remove_batch_jobs_before
    batch_jobs.delete_jobs_before(upper)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 2069, in delete_jobs_before
    self._delete_job(job_id=job_info['job_id'], user_id=job_info['user_id'], propagate_errors=True)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1987, in _delete_job
    shutil.rmtree(job_dir)
  File "/usr/lib64/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink([entry.name](http://entry.name/), dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: '._SUCCESS.crc'
```

Directory contents:
```
[vdboschj@epod023 ~]$ tree -puga /data/projects/OpenEO/j-305816c41ecf463e8255c52ea6f7734c
/data/projects/OpenEO/j-305816c41ecf463e8255c52ea6f7734c
└── [drwxr-sr-x jenkins  eodata  ]  randomforest.model
    ├── [drwxr-sr-x jenkins  eodata  ]  data
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00000-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00000-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00001-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00001-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00002-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00002-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00003-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00003-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00004-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00004-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00005-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00005-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00006-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00006-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00007-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00007-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00008-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00008-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  part-00009-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet
    │   ├── [-rw-r--r-- jenkins  eodata  ]  .part-00009-ea891b43-a92f-4d3c-9f8d-0b1d8d202b1a-c000.snappy.parquet.crc
    │   ├── [-rw-r--r-- jenkins  eodata  ]  _SUCCESS
    │   └── [-rw-r--r-- jenkins  eodata  ]  ._SUCCESS.crc
    └── [drwxr-sr-x jenkins  eodata  ]  metadata
        ├── [-rw-r--r-- jenkins  eodata  ]  part-00000
        ├── [-rw-r--r-- jenkins  eodata  ]  .part-00000.crc
        ├── [-rw-r--r-- jenkins  eodata  ]  _SUCCESS
        └── [-rw-r--r-- jenkins  eodata  ]  ._SUCCESS.crc
```

**Comment by JeroenVerstraelen** [comment]
The tree now looks like this:
[verstraj-local@epod023 ~]$ tree -puga /data/projects/OpenEO/j-c3f4192282ce4007a1b5b5bce474608e
/data/projects/OpenEO/j-c3f4192282ce4007a1b5b5bce474608e
├── [-rw-rw-r-- jenkins  eodata  ]  job_metadata.json
├── [-rw-rw-r-- jenkins  eodata  ]  log
├── [drwxr-sr-x openeo   eodata  ]  randomforest.model
│   ├── [drwxr-sr-x openeo   eodata  ]  data
│   │   ├── [-rw-r--r-- openeo   eodata  ]  part-00000-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet
│   │   ├── [-rw-r--r-- openeo   eodata  ]  .part-00000-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet.crc
│   │   ├── [-rw-r--r-- openeo   eodata  ]  part-00001-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet
│   │   ├── [-rw-r--r-- openeo   eodata  ]  .part-00001-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet.crc
│   │   ├── [-rw-r--r-- openeo   eodata  ]  part-00003-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet
│   │   ├── [-rw-r--r-- openeo   eodata  ]  .part-00003-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet.crc
│   │   ├── [-rw-r--r-- openeo   eodata  ]  part-00005-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet
│   │   ├── [-rw-r--r-- openeo   eodata  ]  .part-00005-37a6888c-5980-4319-8158-23596be4c018-c000.snappy.parquet.crc
│   │   ├── [-rw-r--r-- openeo   eodata  ]  _SUCCESS
│   │   └── [-rw-r--r-- openeo   eodata  ]  ._SUCCESS.crc
│   └── [drwxr-sr-x openeo   eodata  ]  metadata
│       ├── [-rw-r--r-- openeo   eodata  ]  part-00000
│       ├── [-rw-r--r-- openeo   eodata  ]  .part-00000.crc
│       ├── [-rw-r--r-- openeo   eodata  ]  _SUCCESS
│       └── [-rw-r--r-- openeo   eodata  ]  ._SUCCESS.crc
└── [-rw-rw-r-- jenkins  eodata  ]  randomforest.model.tar.gz

**Comment by bossie** [comment]
Not sure I'm quite on board here but why are these things now owned by the openeo user? I would assume that in the context of a batch job, those files would be owned by the user running the batch job (jenkins).

**Comment by JeroenVerstraelen** [comment]
Aha, I figured that was the intended result since the user running the nightly cleaner is the openeo user. The code for this is in the load_ml_model method of backend.py. On a load_ml_model call it will always be the driver that takes the provided job id and goes into its batch job directory. There it unpacks the randomforest.model.tar.gz into a randomforest.model so it can use it to load the actual model. 

So the .tar.gz file is owned by the user running the batch job, the unpacked file is owned by the driver. I don't believe it should cause problems because the user can only download the tar file.
