### ISSUE TITLE
prevent duplicate batch process poll requests

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#269]
Unflattening a process graph can result in duplicate `load_collection` nodes, which are used to schedule SHub batch processes. These duplicates are recognized @ batch process submission time (existing batch processes are recycled to prevent scheduling unnecessary ones) but not yet @ polling time:

https://github.com/Open-EO/openeo-geopyspark-driver/blob/97dc6bc1e70cf004f2f93553fa1cb4dbb35a1fa2/openeogeotrellis/backend.py#L987-L989

This means that a lot of unnecessary poll requests are sent if there are a lot of recycled batch processes. In this particular case the poll requests towards the Batch Processing API ultimately failed with a SocketTimeoutException:

```
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 190, in main
    batch_jobs.poll_sentinelhub_batch_processes(job_info, sentinel_hub_client_alias, vault_token)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 973, in poll_sentinelhub_batch_processes
    batch_processes = reduce(partial(dict_merge_recursive, overwrite=True),
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 974, in <genexpr>
    (batch_request_details(dependency) for dependency in dependencies))
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 969, in batch_request_details
    return {request_id: (batch_processing_service.get_batch_process(request_id),
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 969, in <dictcomp>
    return {request_id: (batch_processing_service.get_batch_process(request_id),
  File "/opt/venv/lib64/python3.8/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/opt/venv/lib64/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o16112.get_batch_process.
: net.jodah.failsafe.FailsafeException: java.net.SocketTimeoutException: connect timed out
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:385)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openeo.geotrellissentinelhub.package$.withRetries(package.scala:59)
	at org.openeo.geotrellissentinelhub.BatchProcessingApi.getBatchProcess(BatchProcessingApi.scala:230)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.$anonfun$get_batch_process$1(BatchProcessingService.scala:154)
	at org.openeo.geotrellissentinelhub.MemoizedCuratorCachedAccessTokenWithAuthApiFallbackAuthorizer.authorized(Authorizer.scala:76)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.authorized(BatchProcessingService.scala:37)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.get_batch_process(BatchProcessingService.scala:153)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at scalaj.http.HttpRequest.doConnection(Http.scala:367)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:492)
	at org.openeo.geotrellissentinelhub.BatchProcessingApi.$anonfun$getBatchProcess$1(BatchProcessingApi.scala:232)
	at org.openeo.geotrellissentinelhub.package$.$anonfun$withRetries$4(package.scala:59)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	... 17 more
```

Preventing these duplicate poll requests makes the polling more efficient and lessens the chance of failed requests towards the Batch Processing API.

**Comment by bossie** [comment]
Process graph for prod job j-433a86225c384e78ba82d926cdacb6db: [process_graph.json.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/10003868/process_graph.json.txt)

The "Sentinel Hub client alias: default" logs (looks like 3 original requests + 103 recycled ones = 106 each poll run) show that requests are duplicated: [job_logs.json.txt](https://github.com/Open-EO/openeo-geopyspark-driver/files/10003867/job_logs.json.txt)
