### ISSUE TITLE
Problem executing a process graph

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-geopyspark-driver#27]
I tried to calculate the [min evi example](https://openeo.org/openeo/news/2019/03/07/openeo-api-040.html) using the r-client with [this](https://github.com/Open-EO/openeo-geopyspark-driver/files/3772329/vito-r-evi-phenology-graph.txt) graph. I got a rather cryptic message as error from the server:

`'list' object has no attribute 'reduce'`

I'm not sure whether I got something wrong in my graph or where to search for the problem in the graph.

**Comment by flahn** [comment]
```
*** Request ***
POST http://openeo.vgt.vito.be/openeo/0.4.2/result
Headers:
                                                             
Accept       application/json, text/xml, application/xml, */*
Content-Type                                 application/json
Body:
{
    "process_graph": {
        "load_collection_IRWJQ5043Z": {
            "process_id": "load_collection",
            "arguments": {
                "id": "SENTINEL2_L2A_SENTINELHUB",
                "spatial_extent": {
                    "west": 16.1,
                    "south": 47.2,
                    "east": 16.6,
                    "north": 48.6
                },
                "temporal_extent": [
                    "2018-01-01",
                    "2018-02-01"
                ]
            }
        },
        "reduce_UQPUG9023M": {
            "process_id": "reduce",
            "arguments": {
                "data": {
                    "from_node": "load_collection_IRWJQ5043Z"
                },
                "dimension": "bands",
                "reducer": {
                    "callback": {
                        "filter_bands_YWRRH8496G": {
                            "process_id": "filter_bands",
                            "arguments": {
                                "bands": [
                                    "B08"
                                ],
                                "common_names": {
                                    "from_argument": "data"
                                }
                            }
                        },
                        "filter_bands_VHKFO3678P": {
                            "process_id": "filter_bands",
                            "arguments": {
                                "bands": [
                                    "B04"
                                ],
                                "common_names": {
                                    "from_argument": "data"
                                }
                            }
                        },
                        "filter_bands_IBHHC6946U": {
                            "process_id": "filter_bands",
                            "arguments": {
                                "bands": [
                                    "B02"
                                ],
                                "common_names": {
                                    "from_argument": "data"
                                }
                            }
                        },
                        "product_PLWIQ4637V": {
                            "process_id": "product",
                            "arguments": {
                                "data": [
                                    {
                                        "from_node": "filter_bands_VHKFO3678P"
                                    },
                                    6
                                ]
                            }
                        },
                        "product_JHWCK4661B": {
                            "process_id": "product",
                            "arguments": {
                                "data": [
                                    {
                                        "from_node": "filter_bands_IBHHC6946U"
                                    },
                                    -7.5
                                ]
                            }
                        },
                        "subtract_ISTCF1676Z": {
                            "process_id": "subtract",
                            "arguments": {
                                "data": [
                                    {
                                        "from_node": "filter_bands_YWRRH8496G"
                                    },
                                    {
                                        "from_node": "filter_bands_VHKFO3678P"
                                    }
                                ]
                            }
                        },
                        "sum_NBALP5556F": {
                            "process_id": "sum",
                            "arguments": {
                                "data": [
                                    1,
                                    {
                                        "from_node": "filter_bands_YWRRH8496G"
                                    },
                                    {
                                        "from_node": "product_PLWIQ4637V"
                                    },
                                    {
                                        "from_node": "product_JHWCK4661B"
                                    }
                                ]
                            }
                        },
                        "divide_SRZYW7428I": {
                            "process_id": "divide",
                            "arguments": {
                                "data": [
                                    {
                                        "from_node": "subtract_ISTCF1676Z"
                                    },
                                    {
                                        "from_node": "sum_NBALP5556F"
                                    }
                                ]
                            }
                        },
                        "product_HKRHQ7369F": {
                            "process_id": "product",
                            "arguments": {
                                "data": [
                                    2.5,
                                    {
                                        "from_node": "divide_SRZYW7428I"
                                    }
                                ]
                            },
                            "result": true
                        }
                    }
                }
            }
        },
        "reduce_MOTKN2224C": {
            "process_id": "reduce",
            "arguments": {
                "data": {
                    "from_node": "reduce_UQPUG9023M"
                },
                "dimension": "temporal",
                "reducer": {
                    "callback": {
                        "min_GKEAK9921E": {
                            "process_id": "min",
                            "arguments": {
                                "data": {
                                    "from_argument": "data"
                                }
                            },
                            "result": true
                        }
                    }
                }
            }
        },
        "save_result_IJFDO5075T": {
            "process_id": "save_result",
            "arguments": {
                "data": {
                    "from_node": "reduce_MOTKN2224C"
                },
                "format": "GTiff"
            },
            "result": true
        }
    },
    "output": {
        "format": "GTiff"
    }
}
 

*** Response ***
Status: 500
Headers:
                                                         
date                        Mon, 16 Dec 2019 08:44:55 GMT
server                                    gunicorn/19.9.0
content-length                                         54
content-type                             application/json
access-control-allow-origin                             *
connection                                          close

Body:
{
  "message": "'list' object has no attribute 'reduce'"
} 
```

**Comment by soxofaan** [comment]
I found the corresponding stack trace in our logs:

```
2019-12-16 09:44:33,531 [INFO - THREAD: ThreadPoolExecutor-0_8 - openeo.driver] : Handling POST http://openeo.vgt.vito.be/openeo/0.4.2/result with data b'{"process_graph":{"load_collection_IRWJQ5043Z":{"process_id":"load_collection","arguments":{"id":"SENTINEL2_L2A_SENTINELHUB","spatial_extent":{"west":16.1,"south":47.2,"east":16.6,"north":48.6},"temporal_extent":["2018-01-01","2018-02-01"]}},"reduce_UQPUG9023M":{"process_id":"reduce","arguments":{"data":{"from_node":"load_collection_IRWJQ5043Z"},"dimension":"bands","reducer":{"callback":{"filter_bands_YWRRH8496G":{"process_id":"filter_bands","arguments":{"bands":["B08"],"common_names":{"from_argument":"data"}}},"filter_bands_VHKFO3678P":{"process_id":"filter_bands","arguments":{"bands":["B04"],"common_names":{"from_argument":"data"}}},"filter_bands_IBHHC6946U":{"process_id":"filter_bands","arguments":{"bands":["B02"],"common_names":{"from_argument":"data"}}},"product_PLWIQ4637V":{"process_id":"product","arguments":{"data":[{"from_node":"filter_bands_VHKFO3678P"},6]}},"product_JHWCK4661B":{"process_id":"product","arguments":{"data":[{"from_node":"filter_bands_IBHHC6946U"},-7.5]}},"subtr...' (1991 bytes)
[2019-12-16 09:44:33,531] INFO in openeo.driver: Handling POST http://openeo.vgt.vito.be/openeo/0.4.2/result with data b'{"process_graph":{"load_collection_IRWJQ5043Z":{"process_id":"load_collection","arguments":{"id":"SENTINEL2_L2A_SENTINELHUB","spatial_extent":{"west":16.1,"south":47.2,"east":16.6,"north":48.6},"temporal_extent":["2018-01-01","2018-02-01"]}},"reduce_UQPUG9023M":{"process_id":"reduce","arguments":{"data":{"from_node":"load_collection_IRWJQ5043Z"},"dimension":"bands","reducer":{"callback":{"filter_bands_YWRRH8496G":{"process_id":"filter_bands","arguments":{"bands":["B08"],"common_names":{"from_argument":"data"}}},"filter_bands_VHKFO3678P":{"process_id":"filter_bands","arguments":{"bands":["B04"],"common_names":{"from_argument":"data"}}},"filter_bands_IBHHC6946U":{"process_id":"filter_bands","arguments":{"bands":["B02"],"common_names":{"from_argument":"data"}}},"product_PLWIQ4637V":{"process_id":"product","arguments":{"data":[{"from_node":"filter_bands_VHKFO3678P"},6]}},"product_JHWCK4661B":{"process_id":"product","arguments":{"data":[{"from_node":"filter_bands_IBHHC6946U"},-7.5]}},"subtr...' (1991 bytes)
[2019-12-16 09:44:33,532] INFO in openeogeotrellis.layercatalog: Creating layer for SENTINEL2_L2A_SENTINELHUB with viewingParameters {'version': '0.4.2', 'from': '2018-01-01', 'to': '2018-02-01', 'left': 16.1, 'right': 16.6, 'top': 48.6, 'bottom': 47.2, 'srs': 'EPSG:4326'}
[2019-12-16 09:44:33,593] INFO in openeogeotrellis.layercatalog: Layer source type: 'sentinel-hub-s2-l2a'
[2019-12-16 09:44:33,594] INFO in openeogeotrellis.layercatalog: band_indices: None
[2019-12-16 09:44:34,428] ERROR in openeo_driver.views: 'list' object has no attribute 'reduce'
Traceback (most recent call last):
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/views.py", line 339, in result
    return execute()
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/views.py", line 352, in execute
    result = evaluate(process_graph, viewingParameters={'version': g.version})
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 54, in evaluate
    return convert_node(processGraph[top_level_node], viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 60, in convert_node
    return apply_process(processGraph['process_id'], processGraph.get('arguments', {}), viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 471, in apply_process
    args = {name: convert_node(expr, viewingParameters) for (name, expr) in args.items()}
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 471, in <dictcomp>
    args = {name: convert_node(expr, viewingParameters) for (name, expr) in args.items()}
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 62, in convert_node
    return convert_node(processGraph['node'], viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 60, in convert_node
    return apply_process(processGraph['process_id'], processGraph.get('arguments', {}), viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 471, in apply_process
    args = {name: convert_node(expr, viewingParameters) for (name, expr) in args.items()}
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 471, in <dictcomp>
    args = {name: convert_node(expr, viewingParameters) for (name, expr) in args.items()}
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 62, in convert_node
    return convert_node(processGraph['node'], viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 60, in convert_node
    return apply_process(processGraph['process_id'], processGraph.get('arguments', {}), viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 524, in apply_process
    return process_function(args, viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 224, in reduce
    return _evaluate_callback_process(args, 'reducer','reduce')
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 251, in _evaluate_callback_process
    return evaluate(callback, args)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 54, in evaluate
    return convert_node(processGraph[top_level_node], viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 60, in convert_node
    return apply_process(processGraph['process_id'], processGraph.get('arguments', {}), viewingParameters)
  File "/data3/hadoop/yarn/local/usercache/openeo/appcache/application_1576080766835_1390/container_e4828_1576080766835_1390_01_000001/venv/lib64/python3.6/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 495, in apply_process
    return image_collection.reduce(process_id,dimension)
AttributeError: 'list' object has no attribute 'reduce'
```

**Comment by jdries** [comment]
I can not get PG to run anymore, closing old issue.
Note that PG was doing filter_bands inside a callback, that may be unsupported...
