### ISSUE TITLE
improve handling of failed batch jobs in job_tracker_v2 on Kubernetes

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#395]
There was this batch job on CreoDIAS that failed (the reason is not important) so no `job_metadata.json` was created and put in S3. The `job_tracker_v2` detected that the job failed and attempted to wrap things up but could not sync its status because it was unable to read this `job_metadata.json`:

```
Failed status sync for job_id='j-b507ac04fb9e417492795a1e47db687a': unexpected NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown

Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 388, in update_statuses
    self._sync_job_status(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 460, in _sync_job_status
    result_metadata = self._batch_jobs.get_results_metadata(job_id, user_id)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 2221, in get_results_metadata
    contents = get_s3_file_contents(str(metadata_file))
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 346, in get_s3_file_contents
    s3_file_object = s3_instance.get_object(
  File "/opt/openeo/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown
```

AFAICT `job_tracker_v2` currently just logs this error so jobs with unrecoverable errors like these will keep being considered in every job_tracker run.

**Comment by bossie** [comment]
Some thoughts:

#390 resorted to swallowing errors from the ETL API so the job status could still be updated if these errors occur so they are considered non-fatal.

The original error reported in this ticket should have been fatal.

`job_tracker` marks jobs as "error" if there is an error (any error) while tracking, whereas `job_tracker_v2` will not update its status at all.

Maybe we should attempt to handle fatal (non-recoverable) and non-fatal (recoverable) differently.

**Comment by jdries** [comment]
I think I fixed the original error mentioned here: a failed job will indeed not have a result metadata file in most cases. On YARN, not having this file resulted in a warning, on k8s an actual error was thrown. I now also log a warning on k8s, the other option would be to either not try reading metadata for failed jobs, or to catch the error elsewhere. In any case, the job tracker should mark the jobs as in error state.
