### ISSUE TITLE
400 Bad Request error from ETL API for failed CreoDIAS batch job

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#400]
> Failed to calculate job costs: 400 Client Error: Bad Request for url: https://etl.terrascope.be/resources

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_tracker_v2.py", line 501, in _sync_job_status
    job_costs = self._job_costs_calculator.calculate_costs(costs_details)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/job_costs_calculator.py", line 56, in calculate_costs
    resource_costs_in_credits = self._etl_api.log_resource_usage(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/integrations/etl_api.py", line 74, in log_resource_usage
    resp.raise_for_status()
  File "/opt/openeo/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://etl.terrascope.be/resources
```

Looks like there is something funky about the `state` property in the request body:

> POST https://etl.terrascope.be/resources {'jobId': 'j-d2ba00e89ec74aef97fb88d1c18b9116', 'jobName': 'timeseries_Basic_Polygon_JSON', 'executionId': 'job-d2ba00e89e-991389f18da42f4c8087', 'userId': '991389f18da42f4c8087f6c1d5a9ed3156f5c04341c4887ab3cf92341220772f@egi.eu', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1681731627000.0, 'jobFinish': 1681731631000.0, 'state': ('FAILED',), 'status': 'UNDEFINED', 'metrics': {'time': {'value': 4000.0, 'unit': 'milliseconds'}, 'processing': {'value': 0.0, 'unit': 'shpu'}}} returned 400: {"status":400,"message":"Bad Request Exception","timestamp":"2023-04-17T11:41:15.201Z","path":"/resources"}

**Comment by bossie** [comment]
Example failing batch job:
```python
import sys
import openeo

URL = "https://openeo-dev.creo.vito.be"
connection = openeo.connect(URL)
l1c = connection.load_collection(
          "SENTINEL1_GRD",
          spatial_extent={'west': 3.758216409030558, 'east': 3.80, 'south': 51.291835566, 'north': 51.32, 'crs': 'EPSG:4326'},
          temporal_extent=["2017-03-07","2017-03-07"],
          bands=['VV']
      )
rgb = l1c.sar_backscatter(options={"implementation_version":"2","debug":True,"tile_size":256})
download = rgb.execute_batch("/tmp/openeo-backscatter-creo.nc", out_format='netCDF', job_options={'driver-memory': '1024M', 'executor-memory': '1024M', 'driver-cores': '1', 'executor-cores': '1', 'max-executors': '2'})
```

FAILED state was fixed:

> logging resource usage {'jobId': 'j-f4fb4b73700c453eb3023aa7d5c92905', 'jobName': None, 'executionId': 'job-f4fb4b7370-jenkins', 'userId': 'jenkins', 'sourceId': 'TerraScope/MEP', 'orchestrator': 'openeo', 'jobStart': 1682347446000.0, 'jobFinish': 1682347486000.0, 'state': 'FAILED', 'status': 'UNDEFINED', 'metrics': {'time': {'value': 40000.0, 'unit': 'milliseconds'}, 'processing': {'value': 0.0, 'unit': 'shpu'}}}
