### ISSUE TITLE
downloading GeoTIFF asset with time dimension fails on CDSE

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#420]
This batch job will succeed but downloading its single GeoTIFF asset fails:

> INFO     openeo.rest.job:job.py:335 Downloading Job result asset 'openEO_2019-09-21Z.tif' from https://openeo-staging.creo.vito.be/openeo/1.1/jobs/j-8bd9ec96c8dd445e8a0d4087f1c496e5/results/assets/.../openEO_2019-09-21Z.tif?expires=1684315327 to /tmp/test_batch_job_geotiff_on_cdse_s2l2a.tif

> openeo.rest.OpenEoApiError: [500] Internal: Server error: NoSuchKey('An error occurred (NoSuchKey) when calling the GetObject operation: Unknown') (ref: r-66055d5c46e1466e90530683598d04d9)

```python
connection = openeo.connect("https://openeo-staging.creo.vito.be").authenticate_oidc()

data_cube = (connection.load_collection("SENTINEL2_L2A")
             .filter_bands(["B04", "B03", "B02"])
             .filter_bbox([2.59003, 51.069, 2.8949, 51.2206])
             .filter_temporal(["2019-09-21", "2019-09-21"]))

data_cube.execute_batch("/tmp/test_batch_job_geotiff_on_cdse_s2l2a.tif")
```

The stack trace that corresponds to this error is this one:
```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/openeo/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/views.py", line 1311, in download_job_result_signed
    return _download_job_result(job_id=job_id, filename=filename, user_id=user_id)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/views.py", line 1097, in _download_job_result
    return _stream_from_s3(result["href"], result)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/views.py", line 1118, in _stream_from_s3
    s3_file_object = s3_instance.get_object(Bucket=bucket, Key=folder)
  File "/opt/openeo/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown
```

FWIW, these batch jobs, on the other hand, will work:

```python
# netCDF output
connection = openeo.connect("https://openeo-staging.creo.vito.be").authenticate_oidc()

data_cube = (connection.load_collection("SENTINEL2_L2A")
             .filter_bands(["B04", "B03", "B02"])
             .filter_bbox([2.59003, 51.069, 2.8949, 51.2206])
             .filter_temporal(["2019-09-21", "2019-09-21"]))

data_cube.execute_batch("/tmp/test_batch_job_geotiff_on_cdse_s2l2a.nc", out_format="netCDF")

```

```python
# reduce_dimension
data_cube = (connection.load_collection("SENTINEL2_L2A")
             .filter_bands(["B04", "B03", "B02"])
             .filter_bbox([2.59003, 51.069, 2.8949, 51.2206])
             .filter_temporal(["2019-09-21", "2019-09-21"])
             .reduce_dimension("t", reducer="mean"))

data_cube.execute_batch("/tmp/test_batch_job_geotiff_on_cdse_s2l2a.tif")
```

**Comment by bossie** [comment]
Closing as a duplicate of #433.

[This request](https://github.com/eu-cdse/openeo-cdse-infra/issues/2#issuecomment-1541602603) now works without the `reduce_dimension` workaround.
