### ISSUE TITLE
aggregate_temporal not specification compliant, not working

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-geopyspark-driver#50]
Upon executing a simple process with `aggregate_temporal` (e.g. via online editor, example given below), an error is thrown and the execution stopped. Upon using `["2019-07-03T00:00:00Z", "2019-07-17T23:59:59Z"]` (not specification compliant) instead of `[ ["2019-07-03T00:00:00Z", "2019-07-17T23:59:59Z"] ]` (compliant) the process is executed, but a faulty raster seems to be returned.

process example, expected to throw array error:
`{
  "process_graph": {
    "load_collection_BEMGN6618B": {
      "arguments": {
        "bands": [
          "B08"
        ],
        "id": "SENTINEL2_L2A_SENTINELHUB",
        "spatial_extent": {
          "west": 5.991754531860351,
          "south": 51.06869305078254,
          "east": 6.013212203979491,
          "north": 51.08141995869366
        },
        "temporal_extent": [
          "2019-07-01T00:00:00Z",
          "2019-07-31T23:59:59Z"
        ]
      },
      "process_id": "load_collection"
    },
    "aggregate_temporal_YEHJA8836E": {
      "arguments": {
        "context": null,
        "data": {
          "from_node": "load_collection_BEMGN6618B"
        },
        "intervals": [
          [
            "2019-07-03T00:00:00Z",
            "2019-07-17T23:59:59Z"
          ]
        ],
        "labels": [],
        "reducer": {
          "process_graph": {
            "1": {
              "process_id": "max",
              "arguments": {
                "data": {
                  "from_parameter": "data"
                }
              },
              "result": true
            }
          }
        },
        "dimension": "t"
      },
      "process_id": "aggregate_temporal"
    },
    "save_result_IINPH1538H": {
      "arguments": {
        "data": {
          "from_node": "aggregate_temporal_YEHJA8836E"
        },
        "format": "GTiff",
        "options": {}
      },
      "process_id": "save_result",
      "result": true
    }
  }
}`

**Comment by soxofaan** [comment]
confirmed

(internal ticket: EP-3659)

**Comment by jdries** [comment]
Agreed, probably this is a leftover from a previous specification of the process.
We get this stack trace:
```
[2020-11-27 08:24:13,871] INFO in openeo_driver.ProcessGraphDeserializer: Using process 'aggregate_temporal' from namespace 'backend'.
[2020-11-27 08:24:14,042] ERROR in openeo_driver.views: An error occurred while calling o3601.mapInstantToInterval.
: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at org.openeo.geotrellis.OpenEOProcesses$$anonfun$16.apply(OpenEOProcesses.scala:80)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.openeo.geotrellis.OpenEOProcesses.mapInstantToInterval(OpenEOProcesses.scala:80)
```
Proposed solution: fix the python side to expect the correct type. The scala implementation now groups the dates in the list two by two, this is no longer necessary in the new spec. So not too hard to fix.

**Comment by jdries** [comment]
Pushed a fix, will close this when available on dev!

**Comment by jdries** [comment]
appears to be fixed on openeo-dev.vito.be
