### ISSUE TITLE
load_stac without spatial_extent from STAC API: AttributeError: 'NoneType' object has no attribute 'reproject'

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geopyspark-driver#517]
Oversight from the `/search` fix in d0d89cf5f4d886be18ff227896424b223bfac7c6: a `load_stac` from a STAC API without a `spatial_extent` fails:

```
Traceback (most recent call last):
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/views.py", line 619, in result
    result = backend_implementation.processing.evaluate(process_graph=process_graph, env=env)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 277, in evaluate
    return evaluate(process_graph=process_graph, env=env)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 348, in evaluate
    result = convert_node(result_node, env=env)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 368, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1480, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1480, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 380, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 368, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1512, in apply_process
    return process_function(args=ProcessArgs(args, process_id=process_id), env=env)
  File "/home/bossie/PycharmProjects/openeo/venv38/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 2091, in load_stac
    return env.backend_implementation.load_stac(url=url, load_params=load_params, env=env)
  File "/home/bossie/PycharmProjects/openeo/openeo-geopyspark-driver/openeogeotrellis/backend.py", line 978, in load_stac
    bbox=requested_bbox.reproject("EPSG:4326").as_wsen_tuple(),
AttributeError: 'NoneType' object has no attribute 'reproject'
```

**Comment by bossie** [comment]
Fixed + added test.
