### ISSUE TITLE
UDF failure on cube without bands dimension

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#539]
from https://discuss.eodc.eu/t/printing-or-logging-from-udf/421/11

Running a UDF on a cube without band dimension (e.g. after reduce_dimension) does not work.

Reproduction snippet
```python
# Omitting imports and connect stuff for brevity
cube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={"west": 5.11, "south": 51.11, "east": 5.12, "north": 51.12},
    temporal_extent=["2021-02-01", "2021-02-20"],
    bands=["B02"],
)
cube = cube.band("B02")
udf = openeo.UDF(
"""
from openeo.udf import XarrayDataCube
def apply_datacube(cube: XarrayDataCube, context: dict) -> XarrayDataCube:
    return cube
"""
)
cube = cube.apply(process=udf)
cube.download("tmp.nc")
```

Fails with 
```
OpenEoApiError: [500] Internal: Server error: Exception during Spark execution: Traceback (most recent call last):
...
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/geopysparkdatacube.py", line 751, in tile_function
    band_coordinates=openeo_metadata.band_dimension.band_names
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 346, in band_dimension
    raise MetadataException("No band dimension")
openeo.metadata.MetadataException: No band dimension
 (ref: r-21160a9887fb4946bc537658fb3b41d4)
```

**Comment by soxofaan** [comment]
FYI: workaround is to (re)add the band dimension before `apply`ing the udf, e.g.
```python
cube = cube.add_dimension(name="bands", label="evi", type="bands")
```
