### ISSUE TITLE
apply_neighborhood overlap and tilesize are not rescaled after super resolution UDF

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#604]
When an UDF doubles changes the resolution from 20m to 10m then the overlap and tilesize from apply_neighborhood are not yet changed to reflect the new resolution. This causes continuity issues when the tiles are stitched back together.

**Comment by JeroenVerstraelen** [comment]
Current blocker: when testing locally in Python it gives this NoSuchMethodError from [Udf.scala](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/udf/Udf.scala#L444):
```
E   Caused by: java.lang.NoSuchMethodError: java.nio.FloatBuffer.rewind()Ljava/nio/FloatBuffer;
E   	at org.openeo.geotrellis.udf.Udf$.$anonfun$runUserCode$2(Udf.scala:444)
E   	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:223)
E   	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:302)
E   	at org.apache.spark.storage.BlockManager.$anonfun$doPutIterator$1(BlockManager.scala:1518)
E   	at org.apache.spark.storage.BlockManager.org$apache$spark$storage$BlockManager$$doPut(BlockManager.scala:1445)
E   	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1509)
E   	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:1332)
E   	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:376)
E   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:327)
E   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
E   	at org.apache.spark.scheduler.Task.run(Task.scala:136)
E   	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
E   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
E   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
E   	... 1 more
```

It must be some issue related to the java version the jar was compiled with and the runtime version.
