### ISSUE TITLE
Failed to start the server

### ISSUE THREAD

**Issue by geostax** [Open-EO/openeo-geopyspark-driver#61]
When i run "python openeogeotrellis/deploy/local.py", i got the mistake below:
```
[2020-12-03 20:37:27,804] 13669 INFO in openeo-geotrellis-local: Created Spark Context <SparkContext master=local[*] appName=openeo-geotrellis-local>
[2020-12-03 20:37:27,830] 13669 INFO in openeo-geotrellis-local: Spark web UI: http://localhost:4040/
[2020-12-03 20:37:28,274] 13669 WARNING in openeo_driver.ProcessGraphDeserializer: Adding process 'pi' without implementation
[2020-12-03 20:37:28,278] 13669 WARNING in openeo_driver.ProcessGraphDeserializer: Adding process 'e' without implementation
[2020-12-03 20:37:28,289] 13669 INFO in openeo_driver.backend: Using driver implementation package openeogeotrellis
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
[2020-12-03 20:37:58,364] 13669 WARNING in kazoo.client: Cannot resolve epod-master1.vgt.vito.be: [Errno 8] nodename nor servname provided, or not known
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
Debugger failed to attach: handshake failed - received >GET / HTTP/1.1< - expected >JDWP-Handshake<
[2020-12-03 20:38:28,367] 13669 WARNING in kazoo.client: Cannot resolve epod-master2.vgt.vito.be: [Errno 8] nodename nor servname provided, or not known
[2020-12-03 20:38:58,369] 13669 WARNING in kazoo.client: Cannot resolve epod-master3.vgt.vito.be: [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "openeogeotrellis/deploy/local.py", line 104, in <module>
    from openeo_driver.views import app, build_backend_deploy_metadata
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openeo_driver/views.py", line 20, in <module>
    from openeo_driver.ProcessGraphDeserializer import evaluate, get_process_registry
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 128, in <module>
    backend_implementation = get_backend_implementation()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openeo_driver/backend.py", line 420, in get_backend_implementation
    _backend_implementation = module.get_openeo_backend_implementation()
  File "/Users/phil/openeo/openeo-geopyspark-driver-master/openeogeotrellis/__init__.py", line 12, in get_openeo_backend_implementation
    return GeoPySparkBackendImplementation()
  File "/Users/phil/openeo/openeo-geopyspark-driver-master/openeogeotrellis/backend.py", line 224, in __init__
    else ZooKeeperServiceRegistry()
  File "/Users/phil/openeo/openeo-geopyspark-driver-master/openeogeotrellis/service_registry.py", line 121, in __init__
    with self._zk_client() as zk:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/phil/openeo/openeo-geopyspark-driver-master/openeogeotrellis/service_registry.py", line 201, in _zk_client
    zk.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kazoo/client.py", line 560, in start
    raise self.handler.timeout_exception("Connection time-out")
kazoo.handlers.threading.KazooTimeoutError: Connection time-out
```
So how can i process it?

**Comment by soxofaan** [comment]
The geopyspark driver indeed assumes and hardcodes quite a bit of components of our setup at VITO. It is not ready yet to run out of the box in an other environment.

**Comment by geostax** [comment]
OK, Thanks!

**Comment by jdries** [comment]
Actually, that concrete problem simply occurs because you don't have a zookeeper instance. We use that for persistence of data (like a database), but there's also an in memory implementation.
Fastest way to use the in memory implementation is to set the environment variable 'TRAVIS' to 1

With respect to setting it up elsewhere, we currently have it running on CreoDIAS and we support layers based on SentinelHub. So those are usable outside of our internal setup!
