### ISSUE TITLE
Downloading results is quite slow for a long time, but recently started to throw timeouts as well

### ISSUE THREAD

**Issue by theroggy** [Open-EO/openeo-geopyspark-driver#631]
Since quite a long time (I guess about a year), downloading the results of a job has become quite slow for larger results.

For a file of +- 700 MB it takes ~10 minutes, which is still reasonable, but for a file of  2.5 GB it takes 1.5 hours, so it seems to become slower and slower with increasing size of the result.

Up till now it eventualy got downloaded, but today I received a few timeouts already a few times, so it seems that it became even slower.
Is this something that can be explained from your side and/or that is known? If not, I 'll do some tests from different locations (e.g. not from our corporate network)...

Timeout stack trace:
```
INFO:cropclassification.util.openeo_util:job {'costs': 40.0, 'created': '2024-01-03T16:34:16Z', 'id': 'j-2401038f43f4484b81ed9a29d5aa91e4', 'status': 'finished', 'title': 's2-agri/s2-agri_2023-02-27_2023-03-05_B02-B03-B04-B08-B11-B12_mean.tif', 'updated': '2024-01-03T16:34:33Z'} finished, so download results
INFO:openeo.rest.job:Downloading Job result asset 'openEO.tif' from https://openeo.vito.be/openeo/1.2/jobs/j-2401038f43f4484b81ed9a29d5aa91e4/results/assets/OWZhMmQ2ZmYyYmE2NWU1ZDQwMjk1NmJmNGI3NzZiMmIwMzM2OWQ0ZDE5ODU1MTdiZjQ4OTFkYTA2ODYwODdjNkBlZ2kuZXU%3D/c4e34182c083b7e857bddad812b8713e/openEO.tif?expires=1704905316 to \\dg3.be\alp\Datagis\satellite_periodic\BEFL\s2-agri\s2-agri_2023-02-27_2023-03-05_B02-B03-B04-B08-B11-B12_mean.tif.download
Traceback (most recent call last):
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\TOOLS\mambaforge\envs\cropclass-dev\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='openeo.vito.be', port=443): Read timed out.

During handling of the above exception, another exception occurred:
```

**Comment by jdries** [comment]
We also started to notice this recently. Not sure if it got worse over time, or if we only notice now as more and more users indeed start to generate large files.

I'm considering an improved setup for the data download part, but we may want to first investigate these timeouts.
Do you eventually manage to download the file?

**Comment by theroggy** [comment]
> I'm considering an improved setup for the data download part, but we may want to first investigate these timeouts. Do you eventually manage to download the file?

Yes, after some retries I was able to get it downloaded.

**Comment by soxofaan** [comment]
From your stack trace I see you are using the python client to download the results. 
Have you played with other ways to download results, e.g. the web editor, manual curl commands, other download managers? It could be that the python client comes with bad download setting defaults for large results. 

Is your PR https://github.com/Open-EO/openeo-python-client/pull/524 related to this for example?

**Comment by theroggy** [comment]
> From your stack trace I see you are using the python client to download the results. Have you played with other ways to download results, e.g. the web editor, manual curl commands, other download managers? It could be that the python client comes with bad download setting defaults for large results.

No, I haven't tried any different tools to download. In general I don't have bad experiences with downloading large files from python, but it is indeed not impossible that small differences in config of backend and front end libraries can cause performance issues.
 
> Is your PR [Open-EO/openeo-python-client#524](https://github.com/Open-EO/openeo-python-client/pull/524) related to this for example?

Partly. It's indeed because the downloads are slow that I noticed that the downloaded files are first completely loaded in memory before anything is written to disk. Nonetheless a chuncked download seems logical in general when working with large files.

**Comment by jdries** [comment]
I think this should have improved, please reopen if not!
