### ISSUE TITLE
weird chunk_polygon issue

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#900]
reported by @Katrijne-at-Vito 

use case that uses old `chunk_polygon`, which is only available on `/openeo/1.1` endpoint, but not on `/openeo/1.2` (new official process is `apply_polygon`).

use case uses `/openeo/1.1` endpoint root, but on starting the job, it fails with

```
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 95, in decorated
    return f(*args, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 939, in start_job
    backend_implementation.batch_jobs.start_job(job_id=job_id, user=user)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1617, in start_job
    self._start_job(job_id, user, _get_vault_token)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1666, in _start_job
    job_dependencies = self._schedule_and_get_dependencies(
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 2181, in _schedule_and_get_dependencies
    convert_node(result_node, env=env.push({
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 453, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1695, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1695, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 471, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 453, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1718, in apply_process
    return evaluate_udp(process_id=process_id, udp=udp, args=args, env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1963, in evaluate_udp
    return _evaluate_process_graph_process(
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1959, in _evaluate_process_graph_process
    return evaluate(process_graph, env=env, do_dry_run=False)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 428, in evaluate
    result = convert_node(top_level_node, env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 453, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1695, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1695, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 485, in convert_node
    return [convert_node(x, env=env) for x in processGraph]
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 485, in <listcomp>
    return [convert_node(x, env=env) for x in processGraph]
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 453, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1729, in apply_process
    return process_function(args=ProcessArgs(args, process_id=process_id), env=env)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 895, in chunk_polygon
    raise ProcessParameterInvalidException(parameter='chunks', process='chunk_polygon', reason=reason)
openeo_driver.errors.ProcessParameterInvalidException: The value passed for parameter 'chunks' in process 'chunk_polygon' is invalid: Polygon type is not supported.
```

**Comment by soxofaan** [comment]
After some more digging, this might not be an api version issue, the error turns out to be about something else:

> openeo_driver.errors.ProcessParameterInvalidException: The value passed for parameter 'chunks' in process 'chunk_polygon' is invalid: Polygon type is not supported.

**Comment by soxofaan** [comment]
In this case the chunk_polygon call is in a UDP of user wig and it gets its polygons from the output of a UDF:
```
      "chunkpolygon1": {
        "process_id": "chunk_polygon",
        "arguments": {
          "chunks": {
            "from_node": "runudf1"
          },
          "data": {
            "from_node": "apply1"
          },
          "mask_value": 999.0,
          "process": {
            "process_graph": {
              "runudf2": {
                "process_id": "run_udf",
```

**Comment by soxofaan** [comment]
I think the best solution in this case is just to migrate to `apply_polygon` and getting rid of `chunk_polygon` usage:

`chunk_polygon(data=..., chunks=..., mask_value=..., process=...)`
->
`apply_polygon(data=..., geometries=..., process-..., mask_value=...)`

**Comment by soxofaan** [comment]
`chunk_polygon` usage was fully eliminated in WIG use case, so this can be closed as "won't fix"
