### ISSUE TITLE
large stac metadata causes driver OOM

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#979]
STAC metadata can get quite large for full year jobs. Driver loads everything into memory to determine metadata. 

Possible solutions:

- use of 'fields extension' to reduce metadata
- use of spark to load metadata from multiple executors
- use a streaming approach to process metadata rather than 'load all at once'

**Comment by bossie** [comment]
@JorisCod do you have a job ID that illustrates this problem?

**Comment by JorisCod** [comment]
We hit the same problem with the new STAC catalog on CDSE
Cfr. j-2412204758e54d3d9f8c0ef5c70ff31b
 
Trying with 12 GB now on Terrascope:
j-2412208af8e44357bce2fec9b9904046

Background teams conversation: https://teams.microsoft.com/l/message/19:2941a270bf8e48a2a8e8a23975051c11@thread.skype/1734690815042?tenantId=9e2777ed-8237-4ab9-9278-2c144d6f6da3&groupId=8c9c739d-2544-4def-8cd4-b65970551b70&parentMessageId=1734360187912&teamName=Unit%20TAP&channelName=openEO-users&createdTime=1734690815042

**Comment by bossie** [comment]
It wasn't immediately apparent from https://github.com/stac-api-extensions/filter#queryables that a `cql2-text` filter requires double quotes around the item property identifier e.g. `"properties.eo:cloud_cover" <= 90`.

Passing the `use-filter-extension` feature flag to `load_stac` enables it.

**Comment by bossie** [comment]
@JorisCod the process graph on Terrascope should work; I wasn't able to fully verify because I don't have `/vitodata` mounted in my batch jobs so please try it yourself.

Make sure to pass `{"use-filter-extension": true}` to the `featureflags` argument of `load_stac`.

**Comment by bossie** [comment]
Re: CDSE, I'm getting some kind of JSON decode error upon paring the STAC API response so I'm debugging that:

```
Traceback (most recent call last):
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 765, in start_main
    main(sys.argv)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 246, in main
    run_driver()
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 207, in run_driver
    run_job(
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/utils.py", line 63, in memory_logging_wrapper
    return function(*args, **kwargs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/deploy/batch_job.py", line 327, in run_job
    result = ProcessGraphDeserializer.evaluate(process_graph, env=env, do_dry_run=tracer)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 441, in evaluate
    result = convert_node(top_level_node, env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 498, in convert_node
    return [convert_node(x, env=env) for x in processGraph]
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 498, in <listcomp>
    return [convert_node(x, env=env) for x in processGraph]
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1796, in apply_process
    the_mask = convert_node(mask_node, env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in apply_process
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1815, in <dictcomp>
    args = {name: convert_node(expr, env=env) for (name, expr) in sorted(args.items())}
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 484, in convert_node
    return convert_node(processGraph['node'], env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 466, in convert_node
    process_result = apply_process(process_id=process_id, args=processGraph.get('arguments', {}),
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 1835, in apply_process
    return process_function(args=ProcessArgs(args, process_id=process_id), env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeo_driver/ProcessGraphDeserializer.py", line 2469, in load_stac
    return env.backend_implementation.load_stac(url=url, load_params=load_params, env=env)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/backend.py", line 770, in load_stac
    return load_stac.load_stac(url, load_params, env, layer_properties={}, batch_jobs=self.batch_jobs)
  File "/opt/openeo/lib/python3.8/site-packages/openeogeotrellis/load_stac.py", line 376, in load_stac
    for itm in intersecting_items:
  File "/opt/openeo/lib/python3.8/site-packages/pystac_client/item_search.py", line 692, in items
    for item in self.items_as_dicts():
  File "/opt/openeo/lib/python3.8/site-packages/pystac_client/item_search.py", line 703, in items_as_dicts
    for page in self.pages_as_dicts():
  File "/opt/openeo/lib/python3.8/site-packages/pystac_client/item_search.py", line 735, in pages_as_dicts
    for page in self._stac_io.get_pages(
  File "/opt/openeo/lib/python3.8/site-packages/pystac_client/stac_api_io.py", line 294, in get_pages
    page = self.read_json(url, method=method, parameters=parameters)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 206, in read_json
    return self.json_loads(txt)
  File "/opt/openeo/lib/python3.8/site-packages/pystac/stac_io.py", line 110, in json_loads
    result = json.loads(txt, *args, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bossie** [comment]
The response in question is actually this (with 200 OK status no less):

```
<html>
    <head>
        <title>Request Rejected</title>
    </head>
    <body>
        The requested URL was rejected. Please consult with your administrator.<br>
        <br>
        Your support ID is: 18298991375635395531<br>
        <br>
        <a href='javascript:history.back();'>[Go Back]</a>
    </body>
</html>
```

https://stac.dataspace.copernicus.eu/v1 seems to have trouble with multiple clauses in `cql2-text` (`... AND ...`); it's not entirely clear why because altering the order sometimes works. `cql2-json` seems to behave better.

**Comment by bossie** [comment]
> https://stac.dataspace.copernicus.eu/v1 seems to have trouble with multiple clauses in `cql2-text` (`... AND ...`); it's not entirely clear why because altering the order sometimes works. `cql2-json` seems to behave better.

This was probably a red herring as the `cql2-text` STAC API request in job `j-2501101058414ba2839584fd30c91b2e` that originally returned a "Request Rejected" now simply succeeds. :man_shrugging: 

Seeing as e.g. STAC API `www.stac.lcfm` does not support POST /search (`Forbidden: Invalid API Key`) a GET request with either a `cql2-text` or a `cql2-json` filter, depending on the conformance classes, seems to way to go.

**Comment by JorisCod** [comment]
@bossie 2 notes:
- We control the www.stac.lcfm, so if the search would be needed still, we can arrange with Sinergise to open it
- How to pass the featureFlags for load_stac? load_Stac in the python client heeft dat argument niet:
https://github.com/Open-EO/openeo-python-client/blob/b6ed141812455ab3e621df5d0267a25b2b20694d/openeo/rest/connection.py#L1346

**Comment by bossie** [comment]
Re: "Request Rejected":

Upon closer inspection, the behavior seems to be that GET /search requests to stac.dataspace with a filter work from the outside but not from within the cluster. POST requests work from everywhere.

Ideally the GET requests get fixed so that:
- we can maintain backwards compatibility because up until now, we've only been sending GET requests;
- www.stac.lcfm will just work.

The assumption is that a STAC API that does not support the Filter Extension will ignore the `filter` param; we always do client side filtering as well.

**Comment by bossie** [comment]
@tcassaert: @JeroenVerstraelen suggested that you might have some insight in this. I'm trying to get this request to work on CDSE: https://stac.dataspace.copernicus.eu/v1/search?limit=20&bbox=-9.000236563891502%2C39.72213715361572%2C-7.789158034529036%2C40.650856515329274&datetime=2020-12-30T00%3A00%3A00Z%2F2020-12-30T23%3A59%3A59.999000Z&collections=sentinel-2-l2a&filter=%22properties.processing%3Aversion%22+%3D+%2705.00%27+and+%22properties.eo%3Acloud_cover%22+%3C%3D+90+and+%22properties.grid%3Acode%22+%3D+%27MGRS-29TNE%27&filter-lang=cql2-text

FYI It works as-is on the VPN, and also on the cluster if I drop the `filter`param.

**Comment by bossie** [comment]
@JorisCod you can get the CDSE job to run* (on dev and staging) if you pass this feature flag to `load_stac` of https://stac.dataspace.copernicus.eu/v1

`{"use-filter-extension": "cql2-json"}`

So instead of simply `true`, you pass `"cql2-json"` to circumvent the issue above.

\* it passes the appropriate cql2-json filters to the STAC APIs and it is able to load the assets from them as well; however, my attempt on dev failed after some executors reported "No space left on device" so YMMV.

**Comment by JorisCod** [comment]
The job on CDSE staging is still running after more than 1 hour:

Batch Job: LCFM_LSF-MONTHLY_V008_2020_29TNE
ID: j-2501151403374f528104aee8d8b9f3a5
Submitted: 1/15/2025, 2:03:37 PM UTC
Updated: 1/15/2025, 3:14:04 PM UTC
Status: running

The job on Terrascope has an error:
ID: j-241219ecc45b4fd2bbeb3a1be302d542
Submitted: 12/19/2024, 9:05:41 PM UTC
Updated: 12/19/2024, 9:37:09 PM UTC
Status: error
(this is on production, if it's not there yet I can retry)

**Comment by bossie** [comment]
> The job on Terrascope has an error: ID: j-241219ecc45b4fd2bbeb3a1be302d542 Submitted: 12/19/2024, 9:05:41 PM UTC Updated: 12/19/2024, 9:37:09 PM UTC Status: error (this is on production, if it's not there yet I can retry)

That Terrascope job is from December so you might want to retry it with the feature flags (can be on production).

**Comment by JorisCod** [comment]
I pasted the wrong job, this is the correct one:

ID: j-2501151408434604bbf7b79e35ccdf90
Submitted: 1/15/2025, 2:08:43 PM UTC
Updated: 1/15/2025, 3:51:04 PM UTC
Status: running

Hanging on: STAC API request: GET https://stac.terrascope.be/search?

**Comment by bossie** [comment]
@JorisCod some quick pointers:

Re: `j-2501151403374f528104aee8d8b9f3a5` on CDSE:
- there's no `"use-filter-extension"` flag on the `load_stac(SCL_20m)` so please add it.

Re: `j-2501151408434604bbf7b79e35ccdf90` on Terrascope:
- driver was killed by YARN because it was using memory beyond its limit;
- try increasing "driver-memory" (you're giving it 2 GB whereas I omitted the `job_options` so it defaulted to 8 GB).

**Comment by bossie** [comment]
Considering GET requests with a `filter` param to https://stac.dataspace.copernicus.eu/v1/ typically get rejected by the CF WAF I've decided to let the HTTP method depend on what the STAC API advertises (links of `rel` "search"), favoring POST over GET.

This:
- avoids having to code exceptions for particular STAC APIs;
- accommodates for for said STAC API.

The Filter Extension will also be used by default, removing the need for feature flags.

@JorisCod, you can leave the feature flags in for now but they can soon be dropped. However, considering POST requests to www.stac.lfcm currently do not work, you'll want to pass feature flag `{"use-filter-extension": "cql2-text"}` to this `load_stac`. If you then get Sinergise to allow POST requests to this STAC API, it can be dropped as well.
